server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: ${DB_PASSWORD}  # 从环境变量读取
  database: 20218374

redis:
  host: localhost
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0

rabbitmq:
  url: amqp://guest:guest@localhost:5672/

jwt:
  secret: ${JWT_SECRET}
  expires_in: 24h 